// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtsXzzK_tmsgCDaDv8zXMznJhZ_yyIDK4',
    appId: '1:112253872362:web:68a987889380f57dee4f93',
    messagingSenderId: '112253872362',
    projectId: 'realchallenge-21260',
    authDomain: 'realchallenge-21260.firebaseapp.com',
    storageBucket: 'realchallenge-21260.firebasestorage.app',
    measurementId: 'G-H8WR2K6WF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-6AXRfgX_sDiRrSJUF5Ji038BVBlr4n8',
    appId: '1:112253872362:android:07a5408d0dd01fa8ee4f93',
    messagingSenderId: '112253872362',
    projectId: 'realchallenge-21260',
    storageBucket: 'realchallenge-21260.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD2NcfZT0nXSLlORXkbGDek59kwGL6N7c',
    appId: '1:112253872362:ios:3da61400733aa3efee4f93',
    messagingSenderId: '112253872362',
    projectId: 'realchallenge-21260',
    storageBucket: 'realchallenge-21260.firebasestorage.app',
    iosBundleId: 'com.example.realChallengeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD2NcfZT0nXSLlORXkbGDek59kwGL6N7c',
    appId: '1:112253872362:ios:3da61400733aa3efee4f93',
    messagingSenderId: '112253872362',
    projectId: 'realchallenge-21260',
    storageBucket: 'realchallenge-21260.firebasestorage.app',
    iosBundleId: 'com.example.realChallengeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtsXzzK_tmsgCDaDv8zXMznJhZ_yyIDK4',
    appId: '1:112253872362:web:037577c9990fb83aee4f93',
    messagingSenderId: '112253872362',
    projectId: 'realchallenge-21260',
    authDomain: 'realchallenge-21260.firebaseapp.com',
    storageBucket: 'realchallenge-21260.firebasestorage.app',
    measurementId: 'G-Z3N1SWBK8W',
  );
}
